# Pass ctrl-s through applications
stty -ixon

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Antigen plugin manager
if [ -f ~/.zsh/antigen.zsh ]; then
    source ~/.zsh/antigen.zsh

    antigen bundle zsh-users/zsh-autosuggestions
    antigen theme romkatv/powerlevel10k
    antigen apply

    # Powerlevel10k theme
    [[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
fi

# Shell environment
if [ -f ~/.env ]; then
    . ~/.env
fi

# Aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Local settings
if [ -f ~/.zshrc_local ]; then
    . ~/.zshrc_local
fi

HISTFILE=~/.zsh_histfile
HISTSIZE=5000
SAVEHIST=10000

setopt autocd extendedglob nomatch notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/manu/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
