# Pass ctrl-s through applications
stty -ixon

# Antigen plugin manager
if [ -f ~/.zsh/antigen.zsh ]; then
    source ~/.zsh/antigen.zsh

    # Only autostart tmux if not running in ssh
    if [ -z "$SSH_CLIENT" ] && command -v tmux &>/dev/null; then
        ZSH_TMUX_AUTOSTART=true
        ZSH_TMUX_AUTOCONNECT=false
        antigen bundle tmux
    fi

    antigen bundle Aloxaf/fzf-tab
    antigen bundle zsh-users/zsh-autosuggestions
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen theme romkatv/powerlevel10k
    antigen bundle agkozak/zsh-z
    antigen apply

    # Powerlevel10k theme
    [[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
fi

# fzf
if [ -f /usr/share/fzf/shell/key-bindings.zsh ]; then
    source /usr/share/fzf/shell/key-bindings.zsh
elif [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
fi

# Shell environment
if [ -f ~/.env ]; then
    source ~/.env
fi

# Aliases
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Local settings
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

HISTFILE=~/.zsh_histfile
HISTSIZE=5000
SAVEHIST=10000

setopt autocd extendedglob nomatch notify histignorespace
bindkey -e

# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
