
name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create dummy files
      run: |
        touch ~/.bashrc ~/.gitconfig ~/.gitcongig_global ~/.aliases
        touch ~/.tmux.conf ~/.env ~/.zshrc
        mkdir ~/.vim ~/.zsh ~/.i3

    - name: Install dotfiles and default packages
      run: echo -e "y\nY" | ./install.sh

    - name: Test that backups are created
      run: |
        test -f ~/.bashrc.bk
        test -f ~/.gitconfig.bk
        test -f ~/.gitconfig.bk
        test -f ~/.aliases.bk
        test -f ~/.tmux.conf.bk
        test -f ~/.env.bk
        test -f ~/.zshrc.bk
        test -d ~/.vim.bk
        test -d ~/.zsh.bk
        test -d ~/.i3.bk

    - name: Test that default packages were installed
      run: |
          command -v zsh
          command -v powerline
